package:
  format-version: "1.0.0"
  name: "crypto_apps_pic32cx_mtg"
  type: "application"
  status: "beta"
  required: false
  version: "1.0.0"

  dependencies:
    - name: "bsp"
      type: "package"
      version: "v3.18.0"
    - name: "csp"
      type: "package"
      version: "v3.18.3"
    - name: "wolfssl"
      type: "package"
      version: "v5.7.0"
    - name: "core"
      type: "package"
      version: "v3.13.1"
    - name: "crypto_v4"
      type: "package"
      version: "MH3-98870-CryptoGUI-Redesign"
